# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/static/img/no-img.png', upload_to='media'),
        ),
    ]
