# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20171030_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='no-img.png', upload_to='media'),
        ),
    ]
